services:
  - type: web
    name: sugestion-data-driven-backend
    runtime: node
    rootDir: functions
    plan: starter
    buildCommand: npm ci
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: SUGESTION_DATA_DRIVEN_API_KEY
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT_BASE64
        sync: false
      - key: FIREBASE_STORAGE_BUCKET
        sync: false
